// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_k_BPaG2mS0t6C5AVw2mwgI-u5kC8tk',
    appId: '1:216451708131:web:0388f989c78098e4b341d6',
    messagingSenderId: '216451708131',
    projectId: 'phongthoviet-faa32',
    authDomain: 'phongthoviet-faa32.firebaseapp.com',
    databaseURL: 'https://phongthoviet-faa32-default-rtdb.firebaseio.com',
    storageBucket: 'phongthoviet-faa32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbO3jPgYN_00sKRYzRJ2XkCalZU_90QM',
    appId: '1:216451708131:android:d4c32e2039cc806db341d6',
    messagingSenderId: '216451708131',
    projectId: 'phongthoviet-faa32',
    databaseURL: 'https://phongthoviet-faa32-default-rtdb.firebaseio.com',
    storageBucket: 'phongthoviet-faa32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-SDqi-E_reuuBSom1lxYYbkMC_wA64kg',
    appId: '1:216451708131:ios:835beb56669510d7b341d6',
    messagingSenderId: '216451708131',
    projectId: 'phongthoviet-faa32',
    databaseURL: 'https://phongthoviet-faa32-default-rtdb.firebaseio.com',
    storageBucket: 'phongthoviet-faa32.firebasestorage.app',
    iosBundleId: 'com.example.phongthoviet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-SDqi-E_reuuBSom1lxYYbkMC_wA64kg',
    appId: '1:216451708131:ios:835beb56669510d7b341d6',
    messagingSenderId: '216451708131',
    projectId: 'phongthoviet-faa32',
    databaseURL: 'https://phongthoviet-faa32-default-rtdb.firebaseio.com',
    storageBucket: 'phongthoviet-faa32.firebasestorage.app',
    iosBundleId: 'com.example.phongthoviet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_k_BPaG2mS0t6C5AVw2mwgI-u5kC8tk',
    appId: '1:216451708131:web:b570627a17e7403cb341d6',
    messagingSenderId: '216451708131',
    projectId: 'phongthoviet-faa32',
    authDomain: 'phongthoviet-faa32.firebaseapp.com',
    databaseURL: 'https://phongthoviet-faa32-default-rtdb.firebaseio.com',
    storageBucket: 'phongthoviet-faa32.firebasestorage.app',
  );

}